/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reposteria;

/**
 *
 * @author Fuad Erikcel
 */
public class PastelesPersonalizados extends javax.swing.JFrame {

    /**
     * Creates new form PastelesPersonalizados
     */
    public PastelesPersonalizados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        txtFechaEntrega = new javax.swing.JTextField();
        lbBetun = new javax.swing.JLabel();
        lbFechaEntrega = new javax.swing.JLabel();
        lbDetalles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        txtBetun = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxTorta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTipoTorta = new javax.swing.JTextField();
        txtPrecioTorta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePP = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSabor = new javax.swing.JTextField();
        txtRelleno = new javax.swing.JTextField();
        lbFechaElaboracion = new javax.swing.JLabel();
        txtFechaElaboracion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pasteles Personalizados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 260, -1));

        lbId.setText("ID:");
        jPanel1.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel1.add(txtFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 230, -1));

        lbBetun.setText("Betún:");
        jPanel1.add(lbBetun, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lbFechaEntrega.setText("Fecha de Entrega:");
        jPanel1.add(lbFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        lbDetalles.setText("Detalles:");
        jPanel1.add(lbDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 230, 60));

        txtBetun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBetunActionPerformed(evt);
            }
        });
        jPanel1.add(txtBetun, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 230, -1));

        jLabel2.setText("Torta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        cbxTorta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxTorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 230, -1));

        jLabel3.setText("Tipo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        txtTipoTorta.setEditable(false);
        jPanel1.add(txtTipoTorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 230, -1));

        txtPrecioTorta.setEditable(false);
        txtPrecioTorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioTortaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecioTorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 230, -1));

        tablePP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Torta", "Precio", "Cantidad", "Sabor", "Relleno", "Fecha de Entrega", "Detalles"
            }
        ));
        jScrollPane2.setViewportView(tablePP);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 700, 140));

        jButton1.setText("Agregar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        jButton2.setText("Eliminar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 230, -1));

        jLabel6.setText("Sabor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jLabel7.setText("Relleno:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));
        jPanel1.add(txtSabor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 230, -1));

        txtRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRellenoActionPerformed(evt);
            }
        });
        jPanel1.add(txtRelleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 230, -1));

        lbFechaElaboracion.setText("Fecha de Elaboracion:");
        jPanel1.add(lbFechaElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(txtFechaElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtPrecioTortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioTortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioTortaActionPerformed

    private void txtRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRellenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRellenoActionPerformed

    private void txtBetunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBetunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBetunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PastelesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PastelesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PastelesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PastelesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PastelesPersonalizados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTorta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBetun;
    private javax.swing.JLabel lbDetalles;
    private javax.swing.JLabel lbFechaElaboracion;
    private javax.swing.JLabel lbFechaEntrega;
    private javax.swing.JLabel lbId;
    private javax.swing.JTable tablePP;
    private javax.swing.JTextField txtBetun;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtFechaElaboracion;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrecioTorta;
    private javax.swing.JTextField txtRelleno;
    private javax.swing.JTextField txtSabor;
    private javax.swing.JTextField txtTipoTorta;
    // End of variables declaration//GEN-END:variables
}
